### ISSUE TITLE
Table styles

### ISSUE THREAD

**Issue by andrewbridge** [audioxide/website#126]
We have basic table styles for our content, but their visibility could be improved. For example, headings could be differentiated, alternate line shading.

[Water.css](https://watercss.kognise.dev/) has similarly minimal styles, but uses a bold heading and an alternate shading colour scheme.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/2941908/103486581-d1acfa00-4df6-11eb-88fc-477130fde09b.png">

**Comment by frederickobrien** [comment]
Nice, looking at that our sans-serif font is probably the way to go too. It's cleaner.

**Comment by andrewbridge** [comment]
Another thing to consider is improving mobile-friendliness of tables. Currently, tables push the whole page out to whatever width it requires on mobile, a wrapper around the table should allow us to just scroll the table rather than the whole page.
