### ISSUE TITLE
Award design

### ISSUE THREAD

**Issue by andrewbridge** [audioxide/website#46]
**Issue originally created 2020-10-26**

---

_**Andre** said:_

> ok, so this is personal preference
> but having seen the ribbon awards
> do we need the text on there?

_**Fred** said:_

> I personally think yes, but style is also on the table

_**Andre** said:_

> i really like how it's done on current/old site, tbh
> with the logo on the ribbon

![image](https://user-images.githubusercontent.com/2941908/97199456-edb56f00-17a7-11eb-9e40-eb8ad979be44.png)

**Comment by frederickobrien** [comment]
More or less resolved by https://github.com/audioxide/website/pull/151/files until we decide to revisit again.
