### ISSUE TITLE
Homepage will break with listening party as a lead post (potentially all non-review content)

### ISSUE THREAD

**Issue by andrewbridge** [audioxide/website#49]
`ReviewLink` now relies on the post having colours.

**Comment by frederickobrien** [comment]
This has possibly become a bigger problem in the last stretch. I tried publishing the _BioShock_ piece last night and the homepage was not at all happy about it. The article kind of appeared in the lead spot _and_ in the articles section, with the featured image showing on neither. The article itself generated ok except again, no featured image.

Deleted the file to keep the site working ok, but makes this a more pressing issue than if it was just listening parties.
