### ISSUE TITLE
Investigate a privacy friendly analytics

### ISSUE THREAD

**Issue by andrewbridge** [audioxide/website#63]
- Previously mentioned goat counter, but it, like many others, is blocked by popular trackers.

**Comment by andrewbridge** [comment]
Probably go with GoatCounter anyway. Alongside it we'll need a good portion of information on the privacy page with full transparency on data collected and methods of blocking the script.

**Comment by frederickobrien** [comment]
Moving over comments from Notion:

@andrewbridge:

> Actually been thinking about this, would be good to discuss more. Using something like https://www.goatcounter.com we'd be able to run basic analytics without cookies and therefore without cookie warnings. That'd mean we'd get far more realistic data (because we could legally collect analytics without getting users to opt in), but we wouldn't get things like bounce rates or user journeys (I believe the developer is working on a way of implementing this kind of thing anonymously though).
> 
> It'd mainly be which pages are getting hit, how many times, and when, plus information about what devices and countries those users were on.
> 
> Would be interesting to know what you're looking for in analytics. We can of course do a double pronged approach where we still optionally load google analytics for deeper insight, but then we're juggling two systems.

@frederickobrien:

> I’m much more attached to Search Console than Google Analytics, so I’ve no real objections to this. Overall traffic, search engine performance, and which pages are being visited are the only things I really care about (I think). The more of a goodie two shoes the website is the happier I am with it.

**Comment by frederickobrien** [comment]
Settled and implemented.
